spring:
  profiles:
    active: dev
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    protocol: smtp
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
      password: ${SPRING_DATA_REDIS_PASSWORD}
      username: ${SPRING_DATA_REDIS_USERNAME}
  servlet:
    multipart:
      max-file-size: 11MB
      max-request-size: 11MB
  quartz:
    job-store-type: jdbc
    properties:
      org:
        quartz:
          jobStore:
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
    jdbc:
      initialize-schema: always
  session:
    store-type: redis
    redis:
      flush-mode: on_save
      namespace: spring:session
    timeout: 1800s

server:
  servlet:
    session:
      cookie:
        name: JSESSIONID
        http-only: true
        secure: false  # Set to true in production with HTTPS
        same-site: lax
        path: /
        max-age: 1800s

app:
  FRONT_END:
    URL: ${APP_FRONTEND_URL}

aws:
  s3:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
    region: ${AWS_REGION}
    bucket-name: ${AWS_BUCKET_NAME}

clamav:
  host: ${CLAM_AV_HOST}
  port: ${CLAM_AV_PORT}

twilio:
  account-sid: ${TWILIO_ACCOUNT_SID}
  auth-token: ${TWILIO_TOKEN}
  phone-number: ${TWILIO_PHONE_NUMBER}

logging:
  level:
    org:
      springframework:
        security: WARN